*** Variables ***
${unq_appPage}    //div[@class='app_logo']
${img_sauceLabsBackpack}    //img[@alt='Sauce Labs Backpack']
${img_sauceLabsBike}    //img[@alt='Sauce Labs Bike Light']
${img_sauceLabsBoltTshirt}    //img[@alt='Sauce Labs Bolt T-Shirt']
${img_sauceLabsFleeceJacket}    //img[@alt='Sauce Labs Fleece Jacket']
${img_sauceLabsOnesie}    //img[@alt='Sauce Labs Onesie']
${img_sauceLabsRedTshirt}    //img[@alt='Test.allTheThings() T-Shirt (Red)']